name: Arlo
favicon: null
layout_spectrum: 0
typography_spectrum: 0.90102
title: Hello
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#171314'
    - '#5d4a4c'
    - '#776f5a'
    - '#a9b5a7'
  brandStrength: 0.125
  lightness: 0.8151041301898658
  saturation: 0.4530898239463568
  rhythmicContrast: 0.34393033501692116
purpose: []
