name: Arlo
favicon: null
layout_spectrum: 0.5166618281509727
typography_spectrum: 0.8240967018064111
title: Hello
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.8626728113740683
  lightness: 0.8151041301898658
  saturation: 0.4530898239463568
  rhythmicContrast: 0.34393033501692116
purpose: []
